### PR TITLE
Remove info and links from 2023, komtek->cybdat

### PR DESCRIPTION
**Pull request by norbye**
As the summer is approaching it's time to reset the information on the site until the plan is set and the new facebook-groups are created(:

We're calling komtek cybdat now right? 👀 

Resolves ABA-931

### CODE REVIEW

**Review by eikhr — APPROVED** [review]
Nice!

**Comment by eikhr** [comment]
I just noticed at `/faq#pakkeliste` we are listing some clothes to bring for events like themed parties. This should also be updated as it includes some stuff for specific events from last year. 
It can maybe be a bit less specific, as I imagine we might forget to update it in the future too.

**Comment by norbye** [comment]
> I just noticed at `/faq#pakkeliste` we are listing some clothes to bring for events like themed parties. This should also be updated as it includes some stuff for specific events from last year. 
> 
> It can maybe be a bit less specific, as I imagine we might forget to update it in the future too.

Good catch! Will remove a few of those less relevant ones

**Comment by norbye** [comment]
> Nice! I noticed that "Kommunikasjonsteknologi" is still written some places

Awesome, should have updated all of those now - and moved the names of the degrees to constants, as NTNU has been known to enjoy renaming stuff now and then so might as well be prepared for the next time

**Pull request merged**
